version: '3.9'

services:
    files-sharing-app:
        build:
            context: .
            dockerfile: Dockerfile
        image: dreamsoft/simple-file-share:latest
        container_name: file-share-container
        ports:
            - "3333:3333"
        volumes:
            - uploads-data:/app/server/uploads
            - sessions-data:/app/server/sessions
            - db-data:/app/server/db-data
        env_file:
            - server/.env.docker

volumes:
    uploads-data:
    sessions-data:
    db-data:
